"""Fleet job errors are redacted before storage and reduced to a plain cause on the dashboard."""

from __future__ import annotations

from tradesync_core.job_errors import MAX_ERROR_CHARS, diagnose, redact


def test_redacts_token_shapes_webhooks_and_labelled_secrets() -> None:
    token = f"{'x' * 24}.abcdef.{'y' * 38}"
    text = (f"failed with {token} posting to https://discord.com/api/webhooks/123/abcDEF_-9 "
            "using Bearer abcdefghijklmnop and api_key=supersecretvalue1")
    out = redact(text)
    for secret in ("x" * 24, "abcDEF_-9", "abcdefghijklmnop", "supersecretvalue1"):
        assert secret not in out
    assert out.count("[redacted]") >= 4
    assert redact("") is None and redact(None) is None
    assert len(redact("z " * 5000)) == MAX_ERROR_CHARS


def test_redaction_can_leave_long_text_uncut() -> None:
    text = "keep " * 1000 + "api_key=supersecretvalue1"
    out = redact(text, limit=None)
    assert len(out) > MAX_ERROR_CHARS and out.startswith("keep keep") and out.endswith("api_key=[redacted]")
    assert redact(text, limit=20) == "keep keep keep keep "


def test_windows_line_endings_are_named() -> None:
    shell = ("Script exited with code 2\nstderr:\n/home/x/scripts/strikezone_health_watchdog.sh: line 14: "
             "set: pipefail\r: invalid option name\n/home/x/s.sh: line 15: $'\\r': command not found")
    env = "Script exited with code 127\nstderr:\n/usr/bin/env: 'python3\r': No such file or directory"
    assert "CRLF" in diagnose(shell) and "CRLF" in diagnose(env)


def test_dns_failures_and_integrity_holds_are_named() -> None:
    dns = ("delivery error: Discord send failed: ClientConnectorDNSError: Cannot connect to host discord.com:443 "
           "ssl:default [Temporary failure in name resolution]")
    assert diagnose(dns) == "A network name lookup failed inside WSL for discord.com, so the job could not reach it."
    hold = ("Script exited with code 1\nstdout:\n## Hyperliquid Quant Integrity Hold\n\n"
            "- `funding_archive_stale`\n- `signal_ledger_stale`\n")
    assert diagnose(hold).startswith("Integrity hold (funding_archive_stale, signal_ledger_stale).")


def test_tracebacks_give_the_exception_or_say_it_was_cut_off() -> None:
    full = ('Script exited with code 1\nstderr:\nTraceback (most recent call last):\n  File "/a/b/weekly.py", line 3, '
            "in <module>\n    main()\nKeyError: 'members'")
    assert diagnose(full) == "Python error: KeyError: 'members'"
    cut = ('Script exited with code 1\nstderr:\nTraceback (most recent call last):\n'
           '  File "/home/x/scripts/strikezone/step6h_autonomous_cycle.py",')
    assert diagnose(cut) == "Python error in step6h_autonomous_cycle.py; the recorded error was cut off before the exception line."


def test_ok_reports_with_a_failing_exit_and_unknown_errors() -> None:
    ok_but_failed = 'Script exited with code 1\nstdout:\n{\n  "ok": true,\n  "dry_run": false\n}'
    assert diagnose(ok_but_failed) == "The script reported ok but exited with code 1."
    assert diagnose("Script exited with code 3\nstdout:\nsomething odd happened") == "something odd happened"
    assert diagnose(None) is None and diagnose("") is None


# --- wallet recovery phrases -------------------------------------------------
#
# Every phrase below is built inside the test from the published wordlist, or
# generated by eth_account in this process and never written anywhere. None is a
# wallet anyone holds.

import hashlib
import random

import pytest

from tradesync_core.bip39_words import WORDS
from tradesync_core.job_errors import SEED_PHRASE_MIN_WORDS, redact_seed_phrases

# SHA-256 of english.txt as published with BIP-39 (one word per line, trailing newline).
BIP39_ENGLISH_SHA256 = "2f5eed53a4727b4bf8880d8f3f199efc90e58503646d9ff8eff3a2ed3b24dbda"


def _phrase(count: int, seed: int) -> list[str]:
    return random.Random(seed).sample(WORDS, count)


def test_the_wordlist_is_the_published_bip39_english_list() -> None:
    assert len(WORDS) == 2048 and len(set(WORDS)) == 2048
    assert hashlib.sha256(("\n".join(WORDS) + "\n").encode("utf-8")).hexdigest() == BIP39_ENGLISH_SHA256


@pytest.mark.parametrize("count", [12, 15, 18, 21, 24])
def test_a_recovery_phrase_of_every_standard_length_is_redacted_whole(count: int) -> None:
    words = _phrase(count, seed=count)
    text = f"restore failed for {' '.join(words)} on retry"
    out = redact(text)
    assert out == "restore failed for [redacted] on retry"
    for word in words:
        assert f" {word} " not in f" {out} "


def test_numbered_comma_separated_and_multiline_phrases_are_redacted() -> None:
    words = _phrase(24, seed=99)
    numbered = "\n".join(f"{i}. {word}" for i, word in enumerate(words, start=1))
    listed = ", ".join(word.upper() for word in words)
    for text in (numbered, listed, " -\n".join(words)):
        out = redact_seed_phrases(f"backup:\n{text}\nend")
        assert out.count("[redacted]") == 1
        assert not any(word in out.lower().split() for word in words)


def test_eleven_wordlist_words_are_left_alone_and_prose_breaks_a_run() -> None:
    eleven = " ".join(_phrase(SEED_PHRASE_MIN_WORDS - 1, seed=11))
    assert redact_seed_phrases(eleven) == eleven
    # Twelve wordlist words interrupted by words outside the list ("the", "and") are not a phrase.
    words = _phrase(12, seed=12)
    prose = " ".join(words[:6]) + " and the " + " ".join(words[6:])
    assert redact_seed_phrases(prose) == prose
    # A long number between two words ends a run: prices are not phrase numbering.
    priced = " ".join(words[:6]) + " 65000 " + " ".join(words[6:])
    assert redact_seed_phrases(priced) == priced


def test_a_real_generated_mnemonic_is_redacted_and_the_rest_survives() -> None:
    eth_account = pytest.importorskip("eth_account")
    eth_account.Account.enable_unaudited_hdwallet_features()
    for words in (12, 24):
        _, phrase = eth_account.Account.create_with_mnemonic(num_words=words)
        out = redact(f"job output: wallet restored from {phrase}. Next step: fund it.", limit=None)
        assert phrase not in out
        assert out == "job output: wallet restored from [redacted]. Next step: fund it."


def test_the_hex_key_and_the_phrase_are_both_redacted_in_one_text() -> None:
    key = "0x" + "".join(random.Random(5).choice("0123456789abcdef") for _ in range(64))
    phrase = " ".join(_phrase(12, seed=5))
    out = redact(f"hex {key} and words {phrase}")
    assert out == "hex [redacted] and words [redacted]"


def test_a_wordlist_word_beside_the_phrase_goes_with_it_and_a_sentence_end_stops_the_run() -> None:
    # "phrase" and "next" are on the wordlist: the first touches the run and is taken with it;
    # the second follows a full stop, which ends a run, so it survives.
    phrase = " ".join(_phrase(12, seed=6))
    assert redact_seed_phrases(f"the phrase {phrase}. Next") == "the [redacted]. Next"


def test_repeated_words_are_not_a_phrase() -> None:
    assert redact_seed_phrases("keep " * 1000) == "keep " * 1000
    words = _phrase(8, seed=8)
    looping = " ".join(words + words)  # sixteen wordlist words, eight distinct
    assert redact_seed_phrases(looping) == looping
